/* Kconfig values for the host build.
 *
 * The firmware gets these generated by the IDF build. Here they are fixed, so a
 * test asserting on a 60-pixel ring stays meaningful regardless of what the
 * booth is configured for.
 */
#pragma once

#define CONFIG_LED_NODE_RING_LEDS 60
#define CONFIG_LED_NODE_RING_OFFSET 0
#define CONFIG_LED_NODE_BRIGHTNESS 80
